import base64
import os
from lxml import etree
from http.server import BaseHTTPRequestHandler
from urllib.parse import urlparse, parse_qs

# Path to the plain text data file generated by your local script
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_FILE = os.path.join(CURRENT_DIR, "data_assets.txt")

class handler(BaseHTTPRequestHandler):
    def do_GET(self):
        # 1. Parse and clean URL parameters
        query = parse_qs(urlparse(self.path).query)
        
        # Default to None if param is missing, then clean the string
        raw_a = query.get('a', [None])[0]
        raw_b = query.get('b', [None])[0]
        
        if not raw_a or not raw_b:
            self.send_error(400, "Missing parameters 'a' or 'b' (e.g., ?a=south-korea&b=brazil)")
            return

        team_a_slug = raw_a.strip().lower()
        team_b_slug = raw_b.strip().lower()

        # 2. Efficiently find the Base64 data in the text file
        svg_a_enc, svg_b_enc = None, None
        
        if os.path.exists(DATA_FILE):
            with open(DATA_FILE, 'r') as f:
                for line in f:
                    if ':' not in line:
                        continue
                    
                    parts = line.split(":", 1)
                    current_slug = parts[0].strip().lower()
                    current_data = parts[1].strip()

                    if current_slug == team_a_slug:
                        svg_a_enc = current_data
                    if current_slug == team_b_slug:
                        svg_b_enc = current_data
                    
                    # Optimization: stop searching if both are found
                    if svg_a_enc and svg_b_enc:
                        break
        
        # 3. Handle missing data error
        if not svg_a_enc or not svg_b_enc:
            missing = team_a_slug if not svg_a_enc else team_b_slug
            self.send_error(404, f"Team key '{missing}' not found in data_assets.txt")
            return

        try:
            # 4. Decode and Parse the SVGs
            parser = etree.XMLParser(remove_blank_text=True)
            tree_a = etree.fromstring(base64.b64decode(svg_a_enc), parser)
            tree_b = etree.fromstring(base64.b64decode(svg_b_enc), parser)

            # 5. The "Surgical Purge" (Removing typography noise)
            for tree in [tree_a, tree_b]:
                for noise in tree.xpath(".//*[@id='typography_labels']"):
                    noise.getparent().remove(noise)

            # 6. Extract components identified in your semantic audit
            # Mascot from Team A, Shield/Silhouette from Team B
            mascot_a = tree_a.xpath(".//*[@id='hero_graphic']")[0]
            shield_b = tree_b.xpath(".//*[@id='primary_silhouette']")[0]

            # 7. Compose the new SVG
            # We use nsmap to handle namespaces automatically and avoid "redefined" errors
            combined_svg = etree.Element("svg", nsmap=tree_b.nsmap)
            
            # Inherit the viewBox and dimensions from the base shield
            combined_svg.set("viewBox", tree_b.get("viewBox", "0 0 100 100"))
            
            # Add the layers
            combined_svg.append(shield_b)
            combined_svg.append(mascot_a)

            # 8. Send the final response
            self.send_response(200)
            self.send_header('Content-type', 'image/svg+xml')
            self.send_header('Access-Control-Allow-Origin', '*')
            self.end_headers()
            
            # Serialize the XML tree to a string
            self.wfile.write(etree.tostring(combined_svg, pretty_print=True))

        except Exception as e:
            # Catch-all for parsing or logic errors
            self.send_error(500, f"SVG Processing Error: {str(e)}")
        